"""create customers and orders tables

Revision ID: ad0c9bb89488
Revises: 
Create Date: 2026-03-28 19:33:59.849796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad0c9bb89488'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP VIEW IF EXISTS products_summary")
    op.drop_table('users')
    op.drop_table('staff1')
    op.drop_table('my_test_table')
    op.drop_table('staff2')
    op.drop_table('sales_data')
    op.drop_index(op.f('idx_products_category'), table_name='products')
    op.drop_index(op.f('idx_products_price'), table_name='products')
    op.drop_index(op.f('idx_products_pricee'), table_name='products')
    op.drop_index(op.f('idx_products_priceee'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('stock', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('products_pkey'))
    )
    op.create_index(op.f('idx_products_priceee'), 'products', ['price'], unique=False)
    op.create_index(op.f('idx_products_pricee'), 'products', ['price'], unique=False)
    op.create_index(op.f('idx_products_price'), 'products', ['price'], unique=False)
    op.create_index(op.f('idx_products_category'), 'products', ['price'], unique=False)
    op.create_table('sales_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('salesperson', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('region', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('sale_amount', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('sale_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('sales_data_pkey'))
    )
    op.create_table('staff2',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('salary', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=50), server_default=sa.text("'mumbai'::character varying"), autoincrement=False, nullable=True),
    sa.CheckConstraint('salary >= 10000', name=op.f('staff2_salary_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('staff2_pkey')),
    sa.UniqueConstraint('email', name=op.f('staff2_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('my_test_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('item_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('my_test_table_pkey'))
    )
    op.create_table('staff1',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('salary', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=50), server_default=sa.text("'mumbai'::character varying"), autoincrement=False, nullable=True),
    sa.CheckConstraint('salary >= 10000', name=op.f('staff1_salary_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('staff1_pkey')),
    sa.UniqueConstraint('email', name=op.f('staff1_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    # ### end Alembic commands ###
